<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
	      <PlatformTarget>x64</PlatformTarget>
        <LangVersion>latest</LangVersion>

        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        
        <DebugType Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">embedded</DebugType>

        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MonkeFrames.Compiler\MonkeFrames.Compiler.csproj"/>
	</ItemGroup>
</Project>
